### PR TITLE
Provider -> Gateway

### PR DESCRIPTION
**Pull request by scothis**
Refs [rfc 0011](https://github.com/projectriff/riff/blob/master/rfc/rfc-0011-streaming-gateways.md)

### CODE REVIEW

**Review by jldec — CHANGES_REQUESTED** [review]
I'm having trouble testing this because we don't have an updated `riff-streaming-runtime.yaml` with the new kafka-gateway CRD.

**Comment by jldec** [comment]
You may want to rebase this PR at the same time, since #182 changed the locations of published release yaml.

**Comment by scothis** [comment]
@jldec try again the the cli and release snapshot are published now, use the latest projectriff/release yaml urls

edit: while you can use the cli to create the resource, https://github.com/projectriff/system/pull/298 is required for kafka to work correctly

**Comment by jldec** [comment]
Thanks @scothis 

I tested again, using `ko apply -f config/riff-streaming.yaml` from build of system [PR 298](https://github.com/projectriff/system/pull/298). This time the gateway deployed without any port clonflict.

I am now seeing the following error with the `time-averager` function when deployed as a streaming processor.

```
$ kubectl logs time-averager-processor-t4jcs-85c4bb5f68-qgstq -c processor
Exception in thread "main" java.lang.RuntimeException: java.nio.file.NoSuchFileException: /var/riff/bindings/input_000/secret/gateway
	at io.projectriff.processor.Processor.resolveStream(Processor.java:251)
	at io.projectriff.processor.Processor.lambda$resolveStreams$2(Processor.java:240)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.projectriff.processor.Processor.resolveStreams(Processor.java:241)
	at io.projectriff.processor.Processor.main(Processor.java:154)
Caused by: java.nio.file.NoSuchFileException: /var/riff/bindings/input_000/secret/gateway
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at io.projectriff.processor.Processor.resolveStream(Processor.java:247)
```

**Review by jldec — APPROVED** [review]
This looks good - tested (manually) the install and function deployment with the streaming runtime.

**Pull request merged**
