### PR TITLE
make install and make dev

### PR DESCRIPTION
**Pull request by jldec**
More convenient way to setup and start the dev server.

### CODE REVIEW

**Comment by scothis** [comment]
Would it be better to delete the Makefile?

**Comment by jldec** [comment]
> Would it be better to delete the Makefile?

That would actually break my workflow

- cd `<repo-directory>`
- git checkout -b `<new-branch>`
- code .
- make dev

i find switching to the website directory and using `npm start` to run the dev server inconvenient (and I'm never sure which npm run commands require `run`).

**Comment by fbiville** [comment]
Note you can do `npm --prefix website install` and `npm --prefix website start` if you want to save a `cd`.

**Comment by jldec** [comment]
nice - thanks @fbiville - (i just recently learned about the `prefix` convention of autoconf.)

**Review by scothis — APPROVED** [review]

**Pull request merged**
