### PR TITLE
Add the s1p2018 keynote video

### PR DESCRIPTION
**Pull request by scothis**
- add Mark's 2018 keynote video
- update /video to be a list of videos (post with 'video' category)
- update nav to point to /video instead of a 2017 keynote
- migrate 2017 keynote video to be a post that is has a video
- update 'riff in 60 seconds' post to be a video
- include video embed in post listings

### CODE REVIEW

**Comment by jldec** [comment]
Thanks @scothis - i like all of it, except the way the home page now mirrors the content from the /blog/ page, just wider - in full window width. I'd be happier if we replaced the home page with entirely new content describing what is riff and what is knative - want to take a first stab at that?

cc. @markfisher

**Comment by scothis** [comment]
> I'd be happier if we replaced the home page with entirely new content describing what is riff and what is knative

agreed

> want to take a first stab at that?

not in this PR 😄

**Comment by scothis** [comment]
I truncated the home page collections to three items each and limited the page width.

screenshot-2018-10-1 riff is for functions

**Review by jldec — APPROVED** [review]
nice interim solution for the home page!

**Pull request merged**
