### PR TITLE
Update location of contour ingress service

### PR DESCRIPTION
**Pull request by scothis**
Refs projectriff/release#168

### CODE REVIEW

**Review by jldec — CHANGES_REQUESTED** [review]
I tried the docker for mac instructions with a knative deployer and that worked
The core runtime instructions did not work for me.

I suggest using the same pattern (`localhost:$INGRESS_PORT`) in the runtime pages as we use on the getting started page for Docker for Mac, instead of trying to cover both minikube and Docker Desktop with the same command.

**Comment by scothis** [comment]
> I tried the docker for mac instructions with a knative deployer and that worked
The core runtime instructions did not work for me.

Both runtimes use the same ingress, if you can access it for one, you can access it for the other.

If you created a knative deployer, deleted it and then created a core deployer with the same name, it's likely that DNS in the cluster hasn't updated yet. Try using different names, or waiting a few minutes.

**Comment by jldec** [comment]
I tried again
- you definitely need to use explicit `localhost` - the IP lookup may work for minikube, but it doesn't work with docker desktop for mac.
- after re-installing from scratch with just the core runtime and using `localhost` i was able to invoke the function with a core deployer.

```
~$ riff core deployer list
NAME     TYPE       REF      URL                                 STATUS   AGE
square   function   square   http://square.default.example.com   Ready    15s

~$ HOST=square.default.example.com
~$ INGRESS=$(kubectl get nodes -ojsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}'):$(kubectl get svc -n contour-external envoy -ojsonpath='{.spec.ports[?(@.port==80)].nodePort}')

~$ echo $INGRESS
192.168.65.3:32270

~$ ping 192.68.65.3
PING 192.68.65.3 (192.68.65.3): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
^C
--- 192.68.65.3 ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss

~$ curl $INGRESS -v -w '\n' -H "Host: $HOST" \
>   -H 'Content-Type: application/json' \
>   -d 7
*   Trying 192.168.65.3...
* TCP_NODELAY set
^C

~$ INGRESS=localhost:32270

~$ curl $INGRESS -v -w '\n' -H "Host: $HOST" \
>   -H 'Content-Type: application/json' \
>   -d 7
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 32270 (#0)
> POST / HTTP/1.1
> Host: square.default.example.com
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 1
> 
* upload completely sent off: 1 out of 1 bytes
< HTTP/1.1 200 OK
< content-type: text/plain
< date: Thu, 23 Apr 2020 08:11:13 GMT
< content-length: 2
< x-envoy-upstream-service-time: 27
< server: envoy
< 
* Connection #0 to host localhost left intact
49
```

**Comment by scothis** [comment]
I'll create a separate issue for the ingress ip on docker for mac.

**Pull request merged**
