### PR TITLE
Add -y to all kapp deploy commands to avoid confirmation prompt

### PR DESCRIPTION
**Pull request by trisberg**
Without it you can't cut and paste the whole block consisting of several kapp commands

### CODE REVIEW

**Comment by scothis** [comment]
Since kapp can delete resources. I think it's valuable to keep the confirmation prompt.

**Comment by trisberg** [comment]
if we keep the confirmation prompt we should have separate command boxes for each command to make copy-n-paste easier. It just makes the whole installation a lot more tedious IMO.

**Comment by trisberg** [comment]
Maybe we could add a `riff system install` to the CLI ;)

**Comment by ekcasey** [comment]
I really like the idea of adding an install command to the CLI.

I also agree that there is a temptation to copy/paste code blocks right now. However these blocks won't work unless they are copied line by line. This is already true of https://github.com/projectriff/charts/blob/master/README.md.

Break them into separate blocks feels safer than auto-agreeing

**Comment by jldec** [comment]
I don't think people will read the kapp prompts, so forcing them to copy, paste, and confirm each step just makes the install more tedious - not really any safer.

I would go with -y for now - and try to minimize the number of copy/pastas required to do an install.

**Comment by trisberg** [comment]
closing for now

**Pull request closed without merging**
